# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  profile:
    # TODO: description
    type: string
    default: production
  cluster_name:
    # TODO: description
    type: string
    default: Test Cluster

  tls-private-key:
    type: secret
    description: |
      A Juju secret URI of a secret containing the private key for peer-to-peer TLS certificates.
